# -*- coding: utf-8 -*-
"""dia01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11_IjphvHFDjBwrOSHIXQ_L9tpbEUVJi5?usp=sharing
"""

import pandas as pd
import matplotlib.pyplot as plt

url_dados = 'https://github.com/BEp0/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'

dados = pd.read_csv(url_dados, compression = 'zip')

dados

dados.head()

dados.tail()

tratados = dados[dados['g-0'] > 0]

tratamento = dados['tratamento'].value_counts()

valor_droga = dados['droga'].unique()

dados['id'].unique()

dados['dose'].unique()

valor_dose = dados['dose'].value_counts()

valor_dose.plot.barh()
plt.title('GRÁFICO DAS DOSES')
plt.ylabel('TIPOS DE DOSES')

tratamento.plot.bar()
plt.title('Tipos de Tratamento', fontsize=16)

dados['tratamento'].value_counts()

cd = dados['tratamento'].value_counts()[0]
cc = dados['tratamento'].value_counts()[1]

total = cd + cc

porcentagem_cd = (cd * 100) / total
porcentagem_cc = (cc * 100) / total

porcentagem_cc, porcentagem_cd

for i in range(0, 35):
  mapa = {f'g-{i}': f'g{i}'}
  dados.rename(columns=mapa, inplace=True)

mapa = {'droga':'composto'}
dados.rename(columns=mapa, inplace=True)

dados # com colunas renomeadas